# Apache vhost pointing at the Nextcloud checkout instead of the default
# /var/www/html document root.
<VirtualHost *:80>
	DocumentRoot /var/www/nextcloud/

	<Directory /var/www/nextcloud/>
		Require all granted
		AllowOverride All
		Options FollowSymLinks MultiViews

		<IfModule mod_dav.c>
			Dav off
		</IfModule>
	</Directory>
</VirtualHost>
