export const appId = 'workflow_ocr'

// This list was taken from https://github.com/tesseract-ocr/tesseract/blob/main/doc/tesseract.1.asc#languages
export const tesseractLanguageMapping = [
	{ label: 'Afrikaans', langCode: 'afr' },
	{ label: 'Amharic', langCode: 'amh' },
	{ label: 'Arabic', langCode: 'ara' },
	{ label: 'Assamese', langCode: 'asm' },
	{ label: 'Azerbaijani', langCode: 'aze' },
	{ label: 'Azerbaijani - Cyrilic', langCode: 'aze_cyrl' },
	{ label: 'Belarusian', langCode: 'bel' },
	{ label: 'Bengali', langCode: 'ben' },
	{ label: 'Tibetan', langCode: 'bod' },
	{ label: 'Bosnian', langCode: 'bos' },
	{ label: 'Breton', langCode: 'bre' },
	{ label: 'Bulgarian', langCode: 'bul' },
	{ label: 'Catalan; Valencian', langCode: 'cat' },
	{ label: 'Cebuano', langCode: 'ceb' },
	{ label: 'Czech', langCode: 'ces' },
	{ label: 'Chinese simplified', langCode: 'chi_sim' },
	{ label: 'Chinese traditional', langCode: 'chi_tra' },
	{ label: 'Cherokee', langCode: 'chr' },
	{ label: 'Corsican', langCode: 'cos' },
	{ label: 'Welsh', langCode: 'cym' },
	{ label: 'Danish', langCode: 'dan' },
	{ label: 'German', langCode: 'deu' },
	{ label: 'Dhivehi', langCode: 'div' },
	{ label: 'Dzongkha', langCode: 'dzo' },
	{ label: 'Greek Modern 1453-', langCode: 'ell' },
	{ label: 'English', langCode: 'eng' },
	{ label: 'English Middle 1100-1500', langCode: 'enm' },
	{ label: 'Esperanto', langCode: 'epo' },
	{ label: 'Math / equation detection module', langCode: 'equ' },
	{ label: 'Estonian', langCode: 'est' },
	{ label: 'Basque', langCode: 'eus' },
	{ label: 'Persian', langCode: 'fas' },
	{ label: 'Faroese', langCode: 'fao' },
	{ label: 'Filipino', langCode: 'fil' },
	{ label: 'Finnish', langCode: 'fin' },
	{ label: 'French', langCode: 'fra' },
	{ label: 'Frankish', langCode: 'frk' },
	{ label: 'French Middle ca.1400-1600', langCode: 'frm' },
	{ label: 'West Frisian', langCode: 'fry' },
	{ label: 'Scottish Gaelic', langCode: 'gla' },
	{ label: 'Irish', langCode: 'gle' },
	{ label: 'Galician', langCode: 'glg' },
	{ label: 'Greek Ancient to 1453', langCode: 'grc' },
	{ label: 'Gujarati', langCode: 'guj' },
	{ label: 'Haitian; Haitian Creole', langCode: 'hat' },
	{ label: 'Hebrew', langCode: 'heb' },
	{ label: 'Hindi', langCode: 'hin' },
	{ label: 'Croatian', langCode: 'hrv' },
	{ label: 'Hungarian', langCode: 'hun' },
	{ label: 'Armenian', langCode: 'hye' },
	{ label: 'Inuktitut', langCode: 'iku' },
	{ label: 'Indonesian', langCode: 'ind' },
	{ label: 'Icelandic', langCode: 'isl' },
	{ label: 'Italian', langCode: 'ita' },
	{ label: 'Italian - Old', langCode: 'ita_old' },
	{ label: 'Javanese', langCode: 'jav' },
	{ label: 'Japanese', langCode: 'jpn' },
	{ label: 'Kannada', langCode: 'kan' },
	{ label: 'Georgian', langCode: 'kat' },
	{ label: 'Georgian - Old', langCode: 'kat_old' },
	{ label: 'Kazakh', langCode: 'kaz' },
	{ label: 'Central Khmer', langCode: 'khm' },
	{ label: 'Kirghiz; Kyrgyz', langCode: 'kir' },
	{ label: 'Kurdish Kurmanji', langCode: 'kmr' },
	{ label: 'Korean', langCode: 'kor' },
	{ label: 'Korean vertical', langCode: 'kor_vert' },
	{ label: 'Lao', langCode: 'lao' },
	{ label: 'Latin', langCode: 'lat' },
	{ label: 'Latvian', langCode: 'lav' },
	{ label: 'Lithuanian', langCode: 'lit' },
	{ label: 'Luxembourgish', langCode: 'ltz' },
	{ label: 'Malayalam', langCode: 'mal' },
	{ label: 'Marathi', langCode: 'mar' },
	{ label: 'Macedonian', langCode: 'mkd' },
	{ label: 'Maltese', langCode: 'mlt' },
	{ label: 'Mongolian', langCode: 'mon' },
	{ label: 'Maori', langCode: 'mri' },
	{ label: 'Malay', langCode: 'msa' },
	{ label: 'Burmese', langCode: 'mya' },
	{ label: 'Nepali', langCode: 'nep' },
	{ label: 'Dutch; Flemish', langCode: 'nld' },
	{ label: 'Norwegian', langCode: 'nor' },
	{ label: 'Occitan post 1500', langCode: 'oci' },
	{ label: 'Oriya', langCode: 'ori' },
	{ label: 'Orientation and script detection module', langCode: 'osd' },
	{ label: 'Panjabi; Punjabi', langCode: 'pan' },
	{ label: 'Polish', langCode: 'pol' },
	{ label: 'Portuguese', langCode: 'por' },
	{ label: 'Pushto; Pashto', langCode: 'pus' },
	{ label: 'Quechua', langCode: 'que' },
	{ label: 'Romanian; Moldavian; Moldovan', langCode: 'ron' },
	{ label: 'Russian', langCode: 'rus' },
	{ label: 'Sanskrit', langCode: 'san' },
	{ label: 'Sinhala; Sinhalese', langCode: 'sin' },
	{ label: 'Slovak', langCode: 'slk' },
	{ label: 'Slovenian', langCode: 'slv' },
	{ label: 'Sindhi', langCode: 'snd' },
	{ label: 'Spanish; Castilian', langCode: 'spa' },
	{ label: 'Spanish; Castilian - Old', langCode: 'spa_old' },
	{ label: 'Albanian', langCode: 'sqi' },
	{ label: 'Serbian', langCode: 'srp' },
	{ label: 'Serbian - Latin', langCode: 'srp_latn' },
	{ label: 'Sundanese', langCode: 'sun' },
	{ label: 'Swahili', langCode: 'swa' },
	{ label: 'Swedish', langCode: 'swe' },
	{ label: 'Syriac', langCode: 'syr' },
	{ label: 'Tamil', langCode: 'tam' },
	{ label: 'Tatar', langCode: 'tat' },
	{ label: 'Telugu', langCode: 'tel' },
	{ label: 'Tajik', langCode: 'tgk' },
	{ label: 'Thai', langCode: 'tha' },
	{ label: 'Tigrinya', langCode: 'tir' },
	{ label: 'Tonga', langCode: 'ton' },
	{ label: 'Turkish', langCode: 'tur' },
	{ label: 'Uighur; Uyghur', langCode: 'uig' },
	{ label: 'Ukrainian', langCode: 'ukr' },
	{ label: 'Urdu', langCode: 'urd' },
	{ label: 'Uzbek', langCode: 'uzb' },
	{ label: 'Uzbek - Cyrilic', langCode: 'uzb_cyrl' },
	{ label: 'Vietnamese', langCode: 'vie' },
	{ label: 'Yiddish', langCode: 'yid' },
	{ label: 'Yoruba', langCode: 'yor' },
]
