name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-20.04
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport@v1.1.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
