name: Build artifact

on:
  push:
    branches:
      - master
      - stable*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: workflow_ocr
      - name: Run Makefile
        run: cd workflow_ocr && make appstore
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: workflow_ocr.tar.gz 
          path: workflow_ocr/build/artifacts/appstore/workflow_ocr.tar.gz      
