name: Build artifact

on:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: workflow_ocr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Makefile
        run: cd ${{ env.APP_NAME }} && make appstore
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APP_NAME }}.tar.gz 
          path: ${{ env.APP_NAME }}/build/artifacts/appstore/${{ env.APP_NAME }}.tar.gz      
