name: PHPUnit-Coverage

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: workflow_ocr

jobs:
  php:
    runs-on: ubuntu-20.04

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.0']
        databases: ['sqlite']
        server-versions: ['stable25']

    name: php${{ matrix.php-versions }}-${{ matrix.databases }}-COVERAGE

    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Checkout app
        uses: actions/checkout@v3
        with:
          path: apps/${{ env.APP_NAME }}
          fetch-depth: 0

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, gd, zip, imagick
          coverage: xdebug

      - name: Set up PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=${{ matrix.databases }} --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
          ./occ app:enable ${{ env.APP_NAME }}
          php -S localhost:8080 &

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v1.1
        id: versions
        continue-on-error: false
        with:
          path: ./apps/${{ env.APP_NAME }}

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Run PHP and JS tests with coverage tracking and merge results
        working-directory: apps/${{ env.APP_NAME }}
        run: make coverage-all

      - name: Upload coverage to Codecov
        working-directory: ./apps/${{ env.APP_NAME }}/coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov 
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }} -Z
