name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: workflow_ocr

jobs:
  php:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']

    name: php${{ matrix.php-versions }}-LINT
    steps:
      - uses: actions/checkout@v2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Lint
        run: composer run lint