name: CS-Fix

on:
  pull_request:

jobs:
  php-cs-fixer:
    name: php-cs-fixer (${{ matrix.php-versions }})
    runs-on: ubuntu-22.04
    # Skip for fork PRs since we cannot push commits back to a fork
    if: github.event.pull_request.head.repo.full_name == github.repository

    strategy:
      matrix:
        php-versions: ['8.5']

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Set up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none

    - name: Install dependencies
      run: composer i

    - name: Run coding standard formatter
      run: composer run cs:fix

    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Apply php-cs-fixer changes
