name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: workflow_ocr

jobs:
  php:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']

    name: php-lint-${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Lint
        run: composer run lint

  nc-app-code-check:
    name: nc-app-code-check
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-versions: ['8.0']
        databases: ['sqlite']
        server-versions: ['stable21']

    steps:
    - name: Checkout server
      uses: actions/checkout@v2
      with:
        repository: nextcloud/server
        ref: ${{ matrix.server-versions }}

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Checkout app
      uses: actions/checkout@v2
      with:
        path: apps/${{ env.APP_NAME }}

    - name: Set up php ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite
        coverage: none

    - name: Install dependencies
      working-directory: apps/${{ env.APP_NAME }}
      run: composer i

    - name: Set up Nextcloud
      env:
        DB_PORT: 4444
      run: |
        mkdir data
        ./occ maintenance:install --verbose --database=${{ matrix.databases }} --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
        ./occ app:enable ${{ env.APP_NAME }}
        php -S localhost:8080 &

    - name: Run NC app code-check
      run: php occ app:check-code ${{ env.APP_NAME }}
